# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5a4d0125da74015bfdf7e5cf928c95c648780c84832fbafef3471e4fe6730c64ab636ffde4cceedf305e444838306234dce03610095dbd039329a5d524f8bc1

test:
  secret_key_base: 479e4658dac51f3e728712f196be6531c472c71acff85d11d5bd790607d1eb746675734110bbcbf486596486bdd3b8272b1dc4a7b0ef31e1da3851178227226e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
